CREATE  TABLE VEM_SER.ENDERECO (
ID_ENDERECO INT PRIMARY KEY NOT NULL,
ID_BAIRRO NUMBER(38) NOT NULL,
LOGRADOURO VARCHAR2(255) NOT NULL,
NUMERO NUMBER(38) NOT NULL,
COMPLEMENTO VARCHAR2(100) NOT NULL,
CEP CHAR(9) NOT NULL,
CONSTRAINT FK_ID_BAIRRO FOREIGN KEY ( ID_BAIRRO ) REFERENCES BAIRRO ( ID_BAIRRO )
); 



CREATE  TABLE VEM_SER.BAIRRO (
ID_BAIRRO INT PRIMARY KEY NOT NULL,
ID_CIDADE NUMBER(38) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
CONSTRAINT FK_ID_CIDADE FOREIGN KEY ( ID_CIDADE ) REFERENCES CIDADE ( ID_CIDADE )
); 


CREATE  TABLE VEM_SER.CIDADE (
ID_CIDADE INT PRIMARY KEY NOT NULL,
ID_ESTADO NUMBER(38) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
CONSTRAINT FK_ID_ESTADO FOREIGN KEY ( ID_ESTADO ) REFERENCES ESTADO ( ID_ESTADO )
); 


CREATE  TABLE VEM_SER.PAIS (
ID_PAIS INT PRIMARY KEY NOT NULL,
NOME NUMBER(10) NOT NULL
);

CREATE  TABLE VEM_SER.ESTADO (
ID_ESTADO NUMBER(38) PRIMARY KEY NOT NULL,
ID_PAIS INT NOT NULL,
NOME VARCHAR2(50) UNIQUE NOT NULL,
CONSTRAINT FK_ID_PAIS FOREIGN KEY ( ID_PAIS ) REFERENCES PAIS (ID_PAIS)
); 

 
CREATE SEQUENCE seq_BAIRRO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO BAIRRO 
(ID_BAIRRO,ID_CIDADE,NOME)
VALUES(SEQ_BAIRRO.nextval,1,'BOA VIAGEM');

INSERT INTO BAIRRO 
(ID_BAIRRO,ID_CIDADE,NOME)
VALUES(SEQ_BAIRRO.nextval,2,'RIO DOCE');







CREATE SEQUENCE seq_CIDADE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO CIDADE 
(Id_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.nextval,1,'RECIFE');

INSERT INTO CIDADE 
(Id_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.nextval,1,'OLINDA');


CREATE SEQUENCE seq_ENDERECO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO ENDERECO 
(ID_ENDERECO,ID_BAIRRO,LOGRADOURO ,NUMERO,COMPLEMENTO,CEP)
VALUES(SEQ_ENDERECO.nextval,1,'RUA BOM JESUS ',22,'MERCADINHO','54705200');

INSERT INTO ENDERECO 
(ID_ENDERECO,ID_BAIRRO,LOGRADOURO ,NUMERO,COMPLEMENTO,CEP)
VALUES(SEQ_ENDERECO.nextval,1,'RUA FRANCISCO ALVES',12,'CASA','55705200');


INSERT INTO ENDERECO 
(ID_ENDERECO,ID_BAIRRO,LOGRADOURO ,NUMERO,COMPLEMENTO,CEP)
VALUES(SEQ_ENDERECO.nextval,2,'RUA EPITACIO',13,'AP','54705222');

INSERT INTO ENDERECO 
(ID_ENDERECO,ID_BAIRRO,LOGRADOURO ,NUMERO,COMPLEMENTO,CEP)
VALUES(SEQ_ENDERECO.nextval,2,'RUA RIO DOCE',10,'CASA','54705232');



CREATE SEQUENCE seq_ESTADO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO ESTADO 
(Id_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.nextval,2,'PERNANBUCO');



CREATE SEQUENCE seq_PAIS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO PAIS 
(Id_PAIS,NOME)
VALUES(SEQ_PAIS.nextval,'BRASIL');

INSERT INTO PAIS 
(Id_PAIS,NOME)
VALUES(SEQ_PAIS.nextval,'ITALIA');


INSERT INTO PAIS 
(Id_PAIS,NOME)
VALUES(SEQ_PAIS.nextval,'FRANÇA');

CREATE SEQUENCE seq_BAIRRO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


ALTER TABLE PAIS MODIFY NOME VARCHAR2(50);


SELECT* FROM PAIS p ;

SELECT * FROM ESTADO e ;

SELECT * FROM CIDADE c ;

SELECT * FROM BAIRRO b ;

SELECT * FROM VEM_SER.ENDERECO e ;


SELECT * FROM PAIS p ORDER BY NOME DESC ;

SELECT LOGRADOURO,CEP FROM ENDERECO e WHERE UPPER(LOGRADOURO)LIKE 'R%';

SELECT * FROM ENDERECO e WHERE UPPER(CEP) LIKE '%0';

SELECT LOGRADOURO ,NUMERO FROM ENDERECO e WHERE NUMERO BETWEEN 1 AND 100;

SELECT LOGRADOURO,CEP FROM ENDERECO e WHERE UPPER(LOGRADOURO) LIKE 'RUA%' ORDER BY CEP DESC;

SELECT COUNT(ID_ENDERECO) FROM ENDERECO e ;

SELECT COUNT(ID_ENDERECO), ID_BAIRRO FROM ENDERECO GROUP BY ID_BAIRRO;


SELECT * FROM VEM_SER.ENDERECO e ;

UPDATE VEM_SER.ENDERECO 
SET 
LOGRADOURO = 'RUA VALADARES',
COMPLEMENTO = 'CASA'
WHERE 
ID_ENDERECO IN (2,3)

UPDATE VEM_SER.ENDERECO 
SET NUMERO = 999999
WHERE ID = 4;

SELECT * FROM VEM_SER.ENDERECO e 
WHERE ID_ENDERECO  = (SELECT MAXX(ID_ENDERECO)FROM VEM_SER.ENDERECO e)

DELETE FROM VEM_SER.ENDERECO e 
WHERE ID_ENDERECO  = (SELECT MAXX(ID_ENDERECO)FROM VEM_SER.ENDERECO)

SELECT * FROM VEM_SER.ENDERECO e 
WHERE NUMERO = 999999

DELETE FROM VEM_SER.ENDERECO e 
WHERE NUMERO =999999

DELETE FROM VEM_SER.ENDERECO e 



 

