
SELECT *
FROM PESSOA p 
RIGHT OUTER JOIN CONTATO c on p.ID_PESSOA = c.ID_PESSOA

SELECT *
FROM PESSOA p 
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA= pxpe.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO=pxpe.ID_ENDERECO)

SELECT *
FROM PESSOA p 
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA= pxpe.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO=pxpe.ID_ENDERECO)
RIGHT OUTER JOIN CONTATO c ON (c.ID_PESSOA = p.ID_PESSOA );

SELECT * 
FROM PESSOA p  
 FULL OUTER  JOIN CONTATO c ON (c.ID_PESSOA=p.ID_PESSOA);



SELECT *
FROM PESSOA p 
FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA= pxpe.ID_PESSOA)
FULL OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO=pxpe.ID_ENDERECO)

SELECT *
FROM PESSOA p 
FULL OUTER JOIN  pxpe ON (p.ID_PESSOA= pxpe.ID_PESSOA)
FULL OUTER JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO=pxpe.ID_ENDERECO)
FULL OUTER JOIN CONTATO c ON (c.ID_PESSOA = p.ID_PESSOA );

SELECT * FROM PESSOA p 
WHERE EXISTS (
SELECT *
FROM PESSOA_X_PESSOA_ENDERECO e
WHERE e.ID_PESSOA = p.ID_PESSOA 
)

SELECT NOME,ID_PESSOA
FROM PESSOA p 

SELECT LOGRADOURO,ID_ENDERECO FROM ENDERECO e 

